name: Django                                  # workflow name

on:
  push:
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-20.04                    # similar to "image" in GitLab
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py check

  bandit:
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - uses: jpetrucciani/bandit-check@master
        with:
          path: '.'
          bandit_flags: '-o bandit-output -f json'

      - run: |
          ls -la
          curl https://gitlab.practical-devsecops.training/-/snippets/3/raw -o upload-results.py
          python3 upload-results.py --host dojo-ha1b304i.lab.practical-devsecops.training --api_key ${{ secrets.API_KEY }} --engagement_id 1 --product_id 1 --lead_id 1 --environment "Production" --result_file bandit-ouput.json --scanner "Bandit Scan"

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py test taskManager


  integration:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - run: echo "This is an integration step"
      - run: exit 1
        continue-on-error: true

  prod:
    runs-on: ubuntu-20.04
    needs: integration
    steps:
      - run: echo "This is a deploy step."
